mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include('polls.urls')),
    path("admin/", admin.site.urls),
    path("rest/", include('polls_api.urls')),
]

mysite/polls/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'questions' # app 이름 정하기
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/result', views.result, name='result'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('signup/', SignupView.as_view()),
]

mysite/polls/models.py
from django.db import models
from django.contrib import admin
from django.utils import timezone
import datetime
from django.contrib.auth.models import User

# Create your models here.
# 1. 모델 생성
# 2. 모델을 테이블에 써 주기 위한 마이그레이션이라는 걸 만들다.
# 3. 모델에 맞는 테이블 생성
# 질문: 여름에 놀러간다면 어디로 갈래?
# 산
# 강
# 바다
# 도심 호캉스

class Question(models.Model):
    question_text = models.CharField(max_length=200, verbose_name='질문')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='생성일') #auto_now_add=True
    owner = models.ForeignKey('auth.User', related_name='questions', on_delete=models.CASCADE, null=True) #User를 참조하는 외래키 생성

    # is_something = models.BooleanField(default=False)
    # average_score = models.FloatField(default=0.0)
    # score = models.FloatField(default=0)
    # is_something = models.BooleanField(default=False)
    # json_field = models.JSONField(default=dict)

    @admin.display(boolean=True, description='최근생성(하루기준)') 
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1) #어제보다 더 최근에 만들어졌다면

    def __str__(self):
        if self.was_published_recently():
            new_badge = 'NEW!!!'
        else:
            new_badge = ''
        return f'{new_badge} 제목: {self.question_text}, 날짜: {self.pub_date}'

class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE) #참조키를 만들었기 때문에 인덱싱
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f'[{self.question.question_text}]  {self.choice_text}'

class Vote(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    voter = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['question', 'voter'], name='unique_voter_for_questions')
        ]

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.db.models import F

from .models import *
from django.http import Http404

from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm

# 4개의 메소드 구현
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # output = ','.join([q.question_text for q in latest_question_list])
    context = {'questions': latest_question_list}
    return render(request, 'polls/index.html', context)
    # return HttpResponse(output)
    # return HttpResponse("Hello, world.")

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id) #500에러 처리

    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")

    # return HttpResponse(f"입력받은 id: {question_id}")
    return render(request, 'polls/detail.html', {'question':question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id) #500에러 처리
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist): #아무것도 선택하지 않았을때 keyerror
        return render(request, 'polls/detail.html', {'question': question, 'error_message': f"선택이 없습니다. id={request.POST['choice']}"})
    else:
        # A 서버에서도 Votes = 1
        # B 서버에서도 Votes = 1
        # 서버에서 하는 게 아니라 DB에서 실행하면 됨, 서버는 여러개지만 디비는 하나이기 때문
        selected_choice.votes = F('votes') + 1 # F는 디비에서 votes의 값을 읽어서 거기서 1을 증가
        selected_choice.save()
        return HttpResponseRedirect(reverse('questions:result', args = (question_id,)))
    
def result(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/result.html', {'question': question})


class SignupView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('user-list')
    template_name = 'registration/signup.html'

mysite/polls/templates/polls/detail.html
<form action={% url 'questions:vote' question.id %} method='post'>
    {% csrf_token %}
    <h1>{{question.question_text}}</h1>
    {% if error_message %}
    <p><strong> {{ error_message }} </strong></p>
    {% endif %}
    
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
        <label for="choice{{ forloop.counter }}">
            {{choice.choice_text}}
        </label>
        <br>
    {%endfor%}

    {% comment %}
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}}</li>
    {%endfor%}
    </ul> {% endcomment %}

<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% if questions %}
<ul>
    {% for question in questions %}
    {% comment %} url 이름으로 id 연결 {% endcomment %}
    <li><a href="{% url 'questions:detail' question.id %}">{{question.question_text}}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>no question</p>
{% endif %}

mysite/polls/templates/polls/result.html
<h1>{{question.question_text}}</h1><br>

{% for choice in question.choice_set.all %}
    <label>
        {{choice.choice_text}} -- {{choice.votes}}
    </label>
    <br>
{%endfor%}